"""
exceptions.py — Custom Exceptions for Project Sane.
Allows precise error classification, tracing, and handling across all modules.
"""

class BaseProjectSaneException(Exception):
    """Base exception class for all errors generated by Project Sane."""
    def __init__(self, message: str, context: str = ""):
        super().__init__(message)
        self.message = message
        self.context = context

    def __str__(self) -> str:
        if self.context:
            return f"[{self.context}] {self.message}"
        return self.message


class AuthenticationError(BaseProjectSaneException):
    """Raised when authentication with Odoo, the support portal, or support gateways fails."""
    pass


class PlanningError(BaseProjectSaneException):
    """Raised when the planning engine fails to generate a valid plan or parse triage findings."""
    pass


class ExecutionError(BaseProjectSaneException):
    """Raised when an active browser run action fails to execute or locate the element."""
    pass


class DocumentationError(BaseProjectSaneException):
    """Raised when site searches or documentation retrieval fails or returns empty/invalid content."""
    pass


class BrowserError(BaseProjectSaneException):
    """Raised when browser start, port binding, CDP connection, or context creation fails."""
    pass


class DuplicationError(BaseProjectSaneException):
    """Raised when target database duplication, neutralization checks, or portal setup fail."""
    pass
